language: node_js
node_js:
  - "8"
branches:
  only:
  - master

before_install:
  - sudo apt-get install python3
  - sudo pip install awscli

script:
  - make build.version

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy.version
    on:
      branch: master
