language: node_js
node_js:
  - "10"
branches:
  only:
  - master
  - v0.11-beta

addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - npm cache --force clean
  - npm install -g firebase-tools

script:
  - npm install
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    message: "Deploying v0.11.dev-$TRAVIS_BUILD_NUMBER-ALPHA"
    script: sh ./scripts/deployment/dev.sh
    on:
      branch: v0.11-beta
  - provider: script
    skip_cleanup: true
    message: "Deploying v0.11-$TRAVIS_BUILD_NUMBER-ALPHA"
    script: sh ./scripts/deployment/prod.sh
    on:
      branch: master
