# Site settings
title: DashboardHub - Pipeline Dashboard
email: eddie@jaoudestudios.com
description: > # this means to ignore newlines until "baseurl:"
  DashboardHub is a Pipeline Dashboard for your Development and Develivery needs.
  Overview of Github, Travis CI and Scrutinizier.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://home.dashboardhub.io" # the base hostname & protocol for your site
twitter_username: dashboardhub
github_username:  dashboardhub

# Build settings
markdown: kramdown
